public struct Lexicon {
    public init() {
    }

    public var words: [Word] {
        vocabularies.map { Word($0.0) }
    }

    public func clue(for word: Word) -> String? {
        vocabularies
            .first(where: { $0.0 == word.stringRepresentation })?
            .1
    }

    private let vocabularies: [(String, String)] = [
        ("THRILL", "A big excitement like on a fast roller coaster."),
        ("OVERTHROW", "To knock a king off his throne."),
        ("GIFT", "A present you get on your birthday."),
        ("ENEMY", "Someone who fights against you."),
        ("PROTECT", "To keep safe from danger."),
        ("PLEAD", "To beg for help nicely."),
        ("SUITABLE", "Just right for the job."),
        ("WEARY", "Very tired after a long day."),
        ("STREAM", "A little river in the woods."),
        ("REVERT", "To go back to how it was before."),
        ("HOWL", "What a wolf does at the moon."),
        ("PREDICT", "To guess what will happen next."),
        ("BASKET", "A container for picnic food."),
        ("MANUFACTURE", "To make things in a factory."),
        ("LIMP", "To walk with a hurt leg."),
        ("DENTIST", "Doctor who fixes your teeth."),
        ("CONTENT", "Happy with what you have."),
        ("DECISION", "Choosing one thing over others."),
        ("WIGGLE", "To shake or twist like a worm."),
        ("THUNDER", "The loud boom after lightning."),
        ("DELICIOUS", "Tastes super yummy."),
        ("LONELY", "Feeling sad without friends."),
        ("BUMPY", "Rough road that shakes the car."),
        ("DUSK", "Time when the sun goes down."),
        ("MUSEUM", "Place full of old treasures."),
        ("PROCESS", "Steps to make something happen."),
        ("PURCHASE", "To buy with money."),
        ("SURVEY", "To look around and check things."),
        ("AFFORD", "Have enough money to buy."),
        ("INDIVIDUAL", "One single person."),
        ("EXPLORE", "To adventure and discover new places."),
        ("CONTINENT", "A huge land like Africa."),
        ("GRASP", "To hold tightly in your hand."),
        ("GIGANTIC", "Super big like a dinosaur."),
        ("BOLT", "To run away very fast."),
        ("POND", "Small water spot with frogs."),
        ("MORAL", "The right thing to do."),
        ("CARE", "To look after someone kindly."),
        ("SKILL", "Something you're good at."),
        ("WINTER", "Cold season with snow."),
        ("SNEAKY", "Tricky and quiet like a fox."),
        ("COUPLE", "Two people together."),
        ("DEVICE", "A gadget like a phone."),
        ("SEVER", "To cut apart completely."),
        ("CHAT", "Talk with a friend."),
        ("VIVID", "Bright colors that pop."),
        ("PALE", "Light skin or color."),
        ("MODEST", "Not bragging about yourself."),
        ("ESCALATE", "To get bigger or worse."),
        ("SOLITARY", "All by yourself."),
        ("HARDSHIP", "A tough time or problem."),
        ("CONDUCTOR", "Leader of a train or orchestra."),
        ("IDENTICAL", "Exactly the same."),
        ("REVIVE", "To wake up or bring back."),
        ("CAPTIVITY", "Being locked up like a bird in a cage."),
        ("SEVERE", "Very strict or bad."),
        ("GIGGLE", "Silly little laugh."),
        ("AVERAGE", "Just okay, not too big or small."),
        ("PLANET", "Earth or Mars in space."),
        ("COSTUME", "Fun outfit for Halloween."),
        ("HAPPY", "Feeling lots of joy."),
        ("JOY", "Super glad feeling."),
        ("BIRTHDAY", "The day you were born."),
        ("INDUSTRIOUS", "Works hard like a busy bee."),
        ("LAUNCH", "To send a rocket up."),
        ("ASTRONOMY", "Studying stars and planets."),
        ("CHARACTER", "Person in a story or your personality."),
        ("PORTABLE", "Easy to carry around."),
        ("ATLAS", "Big book of maps."),
        ("MINIATURE", "Tiny version of something big."),
        ("TANGLED", "All knotted up like hair."),
        ("POLITE", "Saying please and thank you."),
        ("TYPICAL", "Normal or usual."),
        ("YANK", "Pull hard quickly."),
        ("PRESERVE", "Keep safe for later."),
        ("MONTH", "Like January or July."),
        ("WAVE", "Hand hello or ocean water move."),
        ("POLISH", "Make shiny clean."),
        ("CELEBRATE", "Party for something special."),
        ("CONSIDERABLE", "Pretty big amount."),
        ("BUZZ", "Sound a bee makes."),
        ("BURST", "Pop open suddenly."),
        ("CONCENTRATE", "Focus hard on one thing."),
        ("CLUB", "Group of friends or a stick to hit."),
        ("EXACTLY", "Perfectly right."),
        ("DISTANT", "Far away."),
        ("ESSENTIAL", "Really needed."),
        ("GOAL", "What you aim to score."),
        ("REQUIRE", "Must have it."),
        ("CALCULATE", "Figure out with math."),
        ("AMBITION", "Big dream you chase."),
        ("TRADE", "Swap things with someone."),
        ("APPARENT", "Easy to see."),
        ("FLAP", "Wave like a bird's wing."),
        ("NARRATOR", "Person telling the story."),
        ("CONFESS", "Tell your secret."),
        ("SPLENDID", "Really great and awesome."),
        ("COMMUNICATE", "Share ideas by talking."),
        ("CLIMATE", "Weather over a long time."),
        ("RESTART", "Start over again."),
        ("BLEND", "Mix together smoothly."),
        ("SUFFOCATE", "Can't breathe."),
        ("COMPASS", "Tool to find north."),
        ("INSPIRE", "Make someone excited to try."),
        ("PROUD", "Happy about what you did."),
        ("WISDOM", "Smart knowing from experience."),
        ("SUPPLY", "Give what is needed."),
        ("TRIUMPH", "Big win!"),
        ("BOLTS", "Fast runs or metal screws."),
        ("TRANSPORTATION", "Way to get around like bus."),
        ("HALF", "One of two equal parts."),
        ("ANALYZE", "Look closely to understand."),
        ("CERTAIN", "Totally sure."),
        ("ANTONYM", "Opposite word."),
        ("HARSH", "Mean or rough."),
        ("HEARTY", "Big warm laugh."),
        ("SLY", "Clever in a sneaky way."),
        ("BOUNCE", "Jump up and down."),
        ("PILOT", "Flies the airplane."),
        ("JAGGED", "Sharp bumpy edges."),
        ("RELIABLE", "Someone you can trust."),
        ("APPROPRIATE", "Right for the time."),
        ("FIELD", "Big open grass area."),
        ("PAIR", "Two matching things."),
        ("SHAKY", "Wobbly and trembling."),
        ("RUSTY", "Old and orange from weather."),
        ("EXCAVATE", "Dig a big hole."),
        ("DIAGRAM", "Picture that explains."),
        ("HATCH", "Door for chickens or plan idea."),
        ("CAREFREE", "No worries happy."),
        ("MISERY", "Very sad feeling."),
        ("CORNER", "Where two walls meet."),
        ("COMPASSION", "Feel sorry and help."),
        ("ALERT", "Watch out!"),
        ("PEDESTRIAN", "Person walking on sidewalk."),
        ("WILDERNESS", "Big wild forest."),
        ("SIGNAL", "Hand wave to show something."),
        ("ATTRACTIVE", "Looks nice."),
        ("BEVERAGE", "Drink like juice."),
        ("ORIGIN", "Where something starts."),
        ("AVOID", "Stay away from."),
        ("GAZE", "Long look."),
        ("EXHAUSTED", "Super tired out."),
        ("REPEAT", "Do it again."),
        ("SIMPLE", "Easy peasy."),
        ("APPROXIMATE", "About or close to."),
        ("HOST", "Person who welcomes guests."),
        ("PRACTICE", "Do over to get better."),
        ("GRIN", "Big happy smile."),
        ("ADDRESS", "Where you live."),
        ("OCCASION", "Special event."),
        ("FINALLY", "At last."),
        ("ASSIST", "Help out."),
        ("OBSERVE", "Watch carefully."),
        ("SURFACE", "Outside layer."),
        ("STURDY", "Strong and tough."),
        ("LEAF", "Green part on tree."),
        ("SWITCH", "Change or light button."),
        ("APPROACH", "Get closer."),
        ("OCEAN", "Giant salty sea."),
        ("LEADER", "Boss of the group."),
        ("SOURCE", "Where it comes from."),
        ("CONGRATULATE", "Say good job!"),
        ("EXPENSIVE", "Costs a lot."),
        ("BESIDES", "Also or except."),
        ("DEVELOP", "Grow bigger."),
        ("MONARCH", "King or queen."),
        ("DRENCHED", "Soaked wet."),
        ("DISCLOSE", "Tell the secret."),
        ("MASK", "Face cover for pretend."),
        ("GRAB", "Take quickly."),
        ("ZIGZAG", "Wiggly line."),
        ("PROMISE", "Say you will for sure."),
        ("FRIGID", "Freezing cold."),
        ("GENTLE", "Soft and kind."),
        ("MATURE", "Grown up."),
        ("LOYAL", "Sticks by your side."),
        ("AFFORDABLE", "Cheap enough to buy."),
        ("TREMBLE", "Shake from cold or fear."),
        ("SEAL", "Close tight or ocean animal."),
        ("LACK", "Don't have enough."),
        ("CRAVE", "Want badly."),
        ("BUDGE", "Move just a little."),
        ("FAIR", "Equal or fun event."),
        ("WHIMPER", "Soft sad cry."),
        ("GLIDE", "Slide smoothly."),
        ("INVITATION", "Come to my party card."),
        ("PREVENT", "Stop it from happening."),
        ("FAMOUS", "Known by everyone."),
        ("TRAVEL", "Go to new places."),
        ("FOLD", "Bend paper in half."),
        ("DAILY", "Every day."),
        ("WHISPER", "Talk super quiet."),
        ("ROAR", "Loud lion yell."),
        ("EXCESS", "Too much."),
        ("ANNUAL", "Once a year."),
        ("DAWN", "Sun comes up."),
        ("CHAMBER", "Special room."),
        ("HAIL", "Ice from sky or hello."),
        ("PECULIAR", "Strange odd."),
        ("COMPENSATE", "Pay back."),
        ("ILLUMINATE", "Light up."),
        ("CLAW", "Sharp animal nail."),
        ("PREDATOR", "Hunter animal."),
        ("CABIN", "Small wood house."),
        ("HEROIC", "Brave like a superhero."),
        ("SHIVER", "Shake from cold."),
        ("MARCH", "Walk in step or spring month."),
        ("LUXURIOUS", "Fancy comfy."),
        ("PRESENT", "Now or gift."),
        ("LEAK", "Drip out."),
        ("FAN", "Blows air or big supporter."),
        ("SURROUND", "All around."),
        ("MUDDY", "Dirty with mud."),
        ("VILLAGE", "Small town."),
        ("APPLAUSE", "Clap hands."),
        ("RETURN", "Come back."),
        ("CUE", "Hint to start."),
        ("DECORATE", "Make pretty with colors."),
        ("BORDER", "Edge line."),
        ("UNIVERSE", "All space and stars."),
        ("COMPLAIN", "Say you're unhappy."),
        ("OUTCOME", "What happens at end."),
        ("SQUIRM", "Wiggle uncomfortable."),
        ("COUNTRY", "Place like USA."),
        ("GLOW", "Soft shine."),
        ("TRADITION", "Old family way."),
        ("ABSURD", "Silly nonsense."),
        ("CENTAUR", "Half horse half man myth."),
        ("VALUE", "How much it's worth."),
        ("MYTH", "Old pretend story."),
        ("ENTIRE", "All of it."),
        ("HONEST", "Tells truth."),
        ("PATTERN", "Repeating design."),
        ("PRETEND", "Make believe."),
        ("SPRINKLE", "Shake on top lightly."),
        ("DISCARD", "Throw away."),
        ("BENEFIT", "Good thing you get."),
        ("CAUTION", "Be careful."),
        ("CONVINCE", "Make believe it."),
        ("BRAVE", "Not scared."),
        ("PROTAGONIST", "Main story hero."),
        ("LOCATE", "Find where it is."),
        ("BAY", "Part of ocean by land."),
        ("GIANT", "Very tall person."),
        ("STACK", "Pile high."),
        ("TENT", "Camping house."),
        ("DISEASE", "When you're sick."),
        ("QUEASY", "Sick tummy feeling."),
        ("TRUST", "Believe it's safe."),
        ("MINOR", "Small or kid."),
        ("ARREST", "Police catch bad guy."),
        ("DELICATE", "Easy to break."),
        ("SHOVEL", "Digging tool."),
        ("IMPACT", "Big hit."),
        ("BRAIN", "Thinks in your head."),
        ("SERIOUS", "Not joking."),
        ("BASE", "Bottom part."),
        ("ABOLISH", "Get rid of forever."),
        ("ENABLE", "Make able to."),
        ("CENTER", "Middle spot."),
        ("SHIP", "Big boat."),
        ("CONSIDER", "Think about."),
        ("MYSTIFY", "Make puzzled."),
        ("MEADOW", "Flower field."),
        ("CHECK", "Look to see."),
        ("HOBBY", "Fun thing you do."),
        ("OBEY", "Follow rules."),
        ("RELEASE", "Let go."),
        ("SAFE", "No danger."),
        ("NOTE", "Write down or music sound."),
        ("WISE", "Smart choices."),
        ("SOIL", "Dirt ground."),
        ("EXCLAIM", "Yell out loud."),
        ("CONVERT", "Change to new."),
        ("SHY", "Quiet around others."),
        ("SPOTTED", "Dots on it."),
        ("REPRESENT", "Stand for."),
        ("PACE", "Step walk."),
        ("EDGE", "Side rim."),
        ("FOLLOW", "Go after."),
        ("GAP", "Space hole."),
        ("BARE", "No clothes."),
        ("DESCEND", "Go down."),
        ("AGE", "How old."),
        ("DODGE", "Quick move away."),
        ("CONCEPT", "Big idea."),
        ("EXAMINE", "Look close."),
        ("MOCK", "Make fun."),
        ("PREPARE", "Get ready."),
        ("DICTATE", "Tell what to say."),
        ("VISION", "See or dream."),
        ("INTELLIGENT", "Really smart."),
        ("BATCH", "Group bunch."),
        ("DEMOLISH", "Knock down."),
        ("PECK", "Small bite."),
        ("SHADE", "Shadow cool."),
        ("ARRANGE", "Put in order."),
        ("COAST", "Beach shore."),
        ("RARE", "Not common."),
        ("SCRATCH", "Claw mark."),
        ("INVENT", "Make new thing."),
        ("IMITATE", "Copy do same."),
        ("TEAM", "Group players."),
        ("BELONG", "Fit in group."),
        ("LAZY", "Doesn't want work."),
        ("PAST", "Before now."),
        ("ACTUAL", "Real true."),
        ("ROTTEN", "Bad spoiled."),
        ("WEEK", "7 days."),
        ("CENTURY", "100 years."),
        ("FRONTIER", "Wild new land."),
        ("GROAN", "Low sad sound."),
        ("CRUMPLE", "Squish up."),
        ("PEER", "Look close."),
        ("INCLUDE", "Add in."),
        ("ARENA", "Sports place."),
        ("APOLOGIZE", "Say sorry."),
        ("ASTOUND", "Shock surprise."),
        ("ADOPT", "Take as family."),
        ("THICK", "Not thin."),
        ("MOTOR", "Engine power."),
        ("ORDEAL", "Hard trouble."),
        ("MARKET", "Buy sell place."),
        ("SPARKLE", "Twinkle shine."),
        ("ALONE", "By yourself."),
        ("MISCHIEF", "Naughty fun."),
        ("CLEVER", "Smart quick."),
        ("DOME", "Round roof."),
        ("STRATEGY", "Smart plan."),
        ("INCREASE", "Get bigger."),
        ("DENIED", "Said no."),
        ("ADVANTAGE", "Better side."),
        ("MAGNIFICENT", "Wow amazing."),
        ("BURROW", "Animal hole home."),
        ("VISUAL", "See with eyes."),
        ("CROWD", "Lots people."),
        ("SENSITIVE", "Feels easily."),
        ("SUSPEND", "Hang up."),
        ("GREEDY", "Wants too much."),
        ("IMMENSE", "Huge giant."),
        ("HEALTHY", "Strong not sick."),
        ("BUNDLE", "Tied bunch."),
        ("STRIPED", "Lines colors."),
        ("SINK", "Go down water."),
        ("FUEL", "Gas for car."),
        ("ABILITY", "Can do it."),
        ("NECTAR", "Sweet flower juice."),
        ("BLIZZARD", "Big snow storm."),
        ("COMBINE", "Join together."),
        ("COMPLY", "Follow orders."),
        ("LAUNDRY", "Dirty clothes wash."),
        ("PARADE", "Marching show."),
        ("ACCUSE", "Say did bad."),
        ("MOISTURE", "Wet damp."),
        ("MARSH", "Wet muddy land."),
        ("DEFEND", "Protect from attack."),
        ("SWIFT", "Fast quick."),
        ("FRAIL", "Weak break easy."),
        ("GLEAMING", "Shiny bright."),
        ("CONCERN", "Worry about."),
        ("TALON", "Bird sharp claw."),
        ("GALLOP", "Horse fast run."),
        ("FEEBLE", "Very weak."),
        ("BOARD", "Wood piece or get on."),
        ("PAIN", "Ouch hurt."),
        ("STARE", "Long hard look."),
        ("EXHIBIT", "Show off."),
        ("NUMEROUS", "Lots many."),
        ("GUST", "Sudden wind."),
        ("INTENSE", "Very strong."),
        ("NARROW", "Thin not wide."),
        ("DECAY", "Rot bad."),
        ("GATHER", "Come together."),
        ("PRESIDENT", "Country leader."),
        ("TOWER", "Tall building."),
        ("DEED", "What you did."),
        ("SLIGHT", "Small tiny."),
        ("EAGER", "Really want to."),
        ("WEALTHY", "Lots money."),
        ("ACTIVE", "Moving busy."),
        ("SYMBOL", "Picture means something."),
        ("SUMMIT", "Top mountain."),
        ("TOMORROW", "Next day."),
        ("RIPE", "Ready to eat."),
        ("PASSENGER", "Rider in car."),
        ("AUTUMN", "Fall leaves."),
        ("PEACEFUL", "Quiet calm."),
        ("CONTRIBUTE", "Give help."),
        ("ANXIOUS", "Nervous worry."),
        ("MOUNTAIN", "Tall hill."),
        ("CURVED", "Bent round."),
        ("CLEAR", "See through."),
        ("DOZE", "Short sleep."),
        ("GORGE", "Deep valley."),
        ("ROUND", "Circle shape."),
        ("INSECT", "Bug like ant."),
        ("THREAT", "Scary warning."),
        ("DART", "Quick throw."),
        ("NURSERY", "Baby room."),
        ("NAVIGATE", "Find way."),
        ("CHALLENGE", "Hard task."),
        ("RAPID", "Very fast."),
        ("SHRIEK", "High scream."),
        ("IMPRESSIVE", "Wow cool."),
        ("CAUTIOUSLY", "Careful slow."),
        ("RETAIN", "Keep hold."),
        ("ALARM", "Warning bell."),
        ("BASHFUL", "Very shy."),
        ("CAREER", "Job work."),
        ("CHILLY", "Cool cold."),
        ("STRAND", "Beach string."),
        ("OASIS", "Desert water spot."),
        ("EVENING", "Night before bed."),
        ("FLUTTER", "Light wing flap."),
        ("FREEZING", "Ice cold."),
        ("DOZEN", "12 things."),
        ("APPEAR", "Show up."),
        ("PROVIDE", "Give need."),
        ("CONFIDENT", "Sure of self."),
        ("ENVY", "Want others stuff."),
        ("RECALL", "Remember back."),
        ("COAX", "Gently ask."),
        ("SMOOTH", "No bumps."),
        ("COMFORT", "Feel better."),
        ("EVADE", "Dodge away."),
        ("GRAVITY", "Pulls down."),
        ("CRASH", "Big bump."),
        ("HIDE", "Cover up."),
        ("CROWDED", "Too many people."),
        ("ACT", "Pretend do."),
        ("SCOLD", "Yell at bad."),
        ("ARCTIC", "North ice cold."),
        ("SNIFF", "Smell nose."),
        ("FLEE", "Run scared."),
        ("TAUNT", "Tease mean."),
        ("CAGE", "Bars lock."),
        ("ATTENTIVE", "Pay attention."),
        ("ENORMOUS", "Giant big."),
        ("SETTLE", "Sit down stay."),
        ("TERROR", "Big scare."),
        ("CALF", "Baby cow."),
        ("INSTANT", "Right now."),
        ("FOREST", "Trees woods."),
        ("ENDANGER", "Make danger."),
        ("CLING", "Hold tight."),
        ("BORROW", "Use then give back."),
        ("REVEAL", "Show secret."),
        ("PRECIOUS", "Very special."),
        ("SPRING", "Bounce season."),
        ("NIBBLE", "Tiny bite."),
        ("RESPONSE", "Answer back."),
        ("UPSET", "Sad mad."),
        ("DRAWER", "Pull out box."),
        ("RETIRE", "Stop work old."),
        ("RECOGNIZE", "Know who."),
        ("VAST", "Huge wide."),
        ("CRANKY", "Grumpy mad."),
        ("DESERVE", "Earn it."),
        ("CONFUSE", "Mix up."),
        ("PRIVILEGE", "Special right."),
        ("DEEP", "Way down."),
        ("THEORY", "Guess idea."),
        ("ATTRACT", "Pull close."),
        ("PORTION", "Piece part."),
        ("BLOSSOM", "Flower open."),
        ("CLIFF", "High drop."),
        ("DEPRIVE", "Take away."),
        ("ORCHARD", "Fruit trees farm."),
        ("CATERPILLAR", "Worm to butterfly."),
        ("INTERCEPT", "Catch in middle."),
        ("CRAFTY", "Sneaky smart."),
        ("LIMB", "Arm leg."),
        ("DEW", "Morning grass wet."),
        ("CORE", "Middle inside."),
        ("ENTRANCE", "Door in."),
        ("CHILL", "Cold shiver."),
        ("CURIOUS", "Want to know."),
        ("HAZY", "Foggy blurry."),
        ("TRANSLATE", "Change language."),
        ("DANGLE", "Hang loose."),
        ("YESTERDAY", "Day before."),
        ("SPIRAL", "Twisty coil."),
        ("OPPONENT", "Fight against."),
        ("BAGGAGE", "Suitcase stuff."),
        ("RECENT", "Just happened."),
        ("TALENT", "Special skill."),
        ("CUSTOM", "Special way."),
        ("POINTY", "Sharp tip."),
        ("DETECT", "Find hidden."),
        ("RACE", "Fast run compete."),
        ("FLAT", "No hills."),
        ("JOURNEY", "Long trip."),
        ("PROCEED", "Go on."),
        ("COMPLETE", "All done."),
        ("MISTY", "Fog light."),
        ("ACHE", "Hurt throb."),
        ("AWARE", "Know it."),
        ("VISIBLE", "Can see."),
        ("REMARK", "Say comment."),
        ("WOE", "Big sadness."),
        ("SPARSE", "Not many."),
        ("SUPPORT", "Hold up."),
        ("FRAGILE", "Break easy."),
        ("EXASPERATE", "Make mad frustrated."),
        ("BLINK", "Eye shut quick."),
        ("CHEW", "Mouth grind."),
        ("EXULT", "Jump happy."),
        ("GLAD", "Happy good."),
        ("FORTUNATE", "Lucky good."),
        ("DROWSY", "Sleepy eyes."),
        ("TRUNK", "Tree bottom or car back."),
        ("PEAK", "Top point."),
        ("LIBRARY", "Book place."),
        ("TINY", "Very small."),
        ("GLOSSY", "Shiny smooth."),
        ("EXTRAORDINARY", "Not normal wow."),
        ("EARTH", "Our planet."),
        ("SLIP", "Slide fall."),
        ("JUBILATION", "Happy cheer."),
        ("GLANCE", "Quick look."),
        ("EASE", "Easy comfy."),
        ("BRILLIANT", "Bright smart."),
        ("FLOAT", "On water up."),
        ("VALIANT", "Brave hero."),
        ("FEAST", "Big eat party."),
        ("GRACE", "Nice move."),
        ("ANCIENT", "Very old."),
        ("YARD", "Home grass."),
        ("FIERCE", "Wild mean."),
        ("COURTEOUS", "Very polite."),
        ("TELESCOPE", "Star looker."),
        ("DESIRE", "Really want."),
        ("SOLO", "All alone."),
        ("REQUEST", "Ask please."),
        ("BEACH", "Sand water."),
        ("KNOB", "Door turn."),
        ("BRIEF", "Short quick."),
        ("RESPONSIBLE", "Take care."),
        ("GENEROSITY", "Give nice."),
        ("ATMOSPHERE", "Air around."),
        ("DAMP", "Wet little."),
        ("WONDER", "Amazing thing."),
        ("LIZARD", "Scaly crawler."),
        ("CHEER", "Yay shout."),
        ("REMOVE", "Take off."),
        ("BLAND", "No taste."),
        ("MENTION", "Say about."),
        ("ROUTE", "Path way."),
        ("BLAST", "Big boom."),
        ("STEEP", "Hard climb."),
        ("CAPABLE", "Can do."),
        ("CABLE", "Wire cord."),
        ("DISAPPEAR", "Gone vanish."),
        ("ALTITUDE", "High up."),
        ("SPURT", "Sudden shoot."),
        ("FOCUS", "Look hard."),
        ("FOG", "Thick mist."),
        ("FACTORY", "Make stuff place."),
        ("DEDICATE", "Give all."),
        ("ATTEMPT", "Try do."),
        ("TERRIFIED", "Super scared."),
        ("BEAK", "Bird mouth."),
        ("RESPECT", "Honor nice."),
        ("DIVE", "Jump in water."),
        ("AVALANCHE", "Snow slide."),
        ("SCHOLAR", "Smart student."),
        ("WIT", "Funny smart."),
        ("LUXURY", "Fancy nice."),
        ("DISTRESS", "Big trouble."),
        ("MODERN", "New now."),
        ("DOUBT", "Not sure."),
        ("SHABBY", "Old worn."),
        ("OPPOSITE", "Not same."),
        ("FURIOUS", "Very mad."),
        ("SURVIVE", "Stay alive."),
        ("METHOD", "Way how."),
        ("EDIBLE", "Safe eat."),
        ("GLUM", "Sad down."),
        ("PATIENT", "Wait calm."),
        ("TRAGIC", "Sad bad end."),
        ("ATTENTION", "Watch listen."),
        ("REALISTIC", "Like real."),
        ("AWARD", "Prize win."),
        ("NEGATIVE", "Bad no."),
        ("BASIC", "Simple start."),
        ("ILLUSTRATOR", "Picture drawer."),
        ("LIMIT", "Stop max."),
        ("CRADLE", "Baby bed."),
        ("TIMID", "Scared shy."),
        ("MURAL", "Big wall picture."),
        ("ENTERTAIN", "Fun make."),
        ("PEST", "Bother bug."),
        ("HABIT", "Do every day."),
        ("ASSUME", "Think is."),
        ("SLUGGISH", "Slow lazy."),
        ("RISE", "Go up."),
        ("PREFER", "Like best."),
        ("WITHDRAW", "Pull back."),
        ("PASTIME", "Fun free time."),
        ("SOLE", "Only or shoe bottom."),
        ("HOOF", "Horse foot."),
        ("DISTRACT", "Take away attention."),
        ("COVERED", "Hidden top."),
        ("CHAMPION", "Big winner."),
        ("MELT", "Turn liquid."),
        ("NONCHALANT", "Cool calm."),
        ("CREAK", "Door squeak."),
        ("SCATTER", "Spread out."),
        ("ROW", "Line or fight."),
        ("DRIFT", "Float slow."),
        ("CAVE", "Dark rock home."),
        ("SELDOM", "Not often."),
        ("SEARCH", "Look for."),
        ("SCENE", "Place picture."),
        ("NOTICE", "See spot."),
        ("ABUSE", "Hurt bad."),
        ("ASCEND", "Go up."),
        ("ADVICE", "Help say."),
        ("WARM", "Not cold."),
        ("FRIGHTEN", "Scare afraid."),
        ("PAUSE", "Stop little."),
        ("VOLUNTEER", "Help free."),
        ("STARVE", "No food hungry."),
        ("COMPOSE", "Make song."),
        ("HARM", "Hurt bad."),
        ("ARTIST", "Draw paint."),
        ("WORRY", "Afraid bad."),
        ("SHELTER", "Safe cover."),
        ("BRIGHT", "Light shine."),
        ("PERISH", "Die gone."),
        ("DECLINE", "Say no go down."),
        ("HERD", "Animal group."),
        ("LOCAL", "Near home."),
        ("ROUTINE", "Same every day."),
        ("SILENT", "No sound."),
        ("PASTURE", "Grass for cows."),
        ("SENSELESS", "No sense silly."),
        ("SHELL", "Outside hard."),
        ("BEND", "Curve not straight."),
        ("CALM", "Peace quiet."),
        ("RESIDENT", "Lives there."),
        ("SAUNTER", "Walk slow relaxed."),
        ("LIVELY", "Full energy."),
        ("CAPTURE", "Catch hold."),
        ("MASTER", "Best expert."),
        ("DUSTY", "Dirty dust."),
        ("SOB", "Cry loud."),
        ("BLOOM", "Flower open."),
        ("CREW", "Work team."),
        ("BRANCH", "Tree arm."),
        ("CIRCULAR", "Round circle."),
        ("ELEGANT", "Pretty fancy."),
        ("GUARDIAN", "Protector watcher."),
        ("AGGRESSIVE", "Pushy mean."),
        ("WANDER", "Walk no plan."),
        ("RELAX", "Rest easy."),
        ("WEAK", "Not strong."),
        ("RESCUE", "Save danger."),
        ("TOUR", "Visit look."),
        ("ARTISTIC", "Creative draw."),
        ("GASP", "Air surprise."),
        ("KNIGHT", "Castle fighter."),
        ("FILTHY", "Very dirty."),
        ("SELFISH", "Only me."),
        ("RESIST", "Fight against."),
        ("FATAL", "Deadly bad."),
        ("SIBLING", "Brother sister."),
        ("RUMOR", "Gossip talk."),
        ("PERMIT", "Say okay."),
        ("ACHIEVEMENT", "Big success."),
        ("REVERSE", "Back way."),
        ("BOLD", "Brave daring."),
        ("ROUGH", "Bumpy not smooth."),
        ("STEER", "Drive direct."),
        ("PLAN", "Idea steps."),
        ("REACH", "Get to."),
        ("SOLUTION", "Fix answer."),
        ("VENTURE", "Risky try."),
        ("AVAILABLE", "Ready use."),
        ("SEED", "Plant baby."),
        ("MISTRUST", "Not trust."),
        ("PACK", "Group bundle."),
        ("PASSAGE", "Way through."),
        ("CONNECT", "Join link."),
        ("DISASTER", "Big bad thing."),
        ("BLUSH", "Face red shy."),
        ("SYNONYM", "Same meaning word."),
        ("PLUNGE", "Jump deep."),
        ("GRATEFUL", "Thankful happy."),
        ("STEADY", "Not shake."),
        ("SCHEDULE", "Plan times."),
        ("AWKWARD", "Clumsy weird."),
        ("ADJUST", "Change fit."),
        ("NATION", "Big country."),
        ("COMPETITION", "Race win."),
        ("REIGN", "King rule."),
        ("OUTSTANDING", "Best great."),
        ("RATE", "How fast."),
        ("FRESH", "New clean."),
        ("HUMBLE", "Not proud."),
        ("CONCLUDE", "End finish."),
        ("SLIDE", "Smooth down."),
        ("AGREE", "Say yes same."),
        ("TREASURE", "Shiny value."),
        ("ACCOMPLISH", "Do finish."),
        ("DANGEROUS", "Risk hurt."),
        ("CONTAIN", "Hold inside."),
        ("SAIL", "Boat wind."),
        ("RISK", "Chance bad."),
        ("HEAP", "Big pile."),
        ("WEED", "Bad plant."),
        ("IDEA", "Thought new."),
        ("REFLECT", "Think back mirror."),
        ("COURSE", "Path class."),
        ("FLUFFY", "Soft fuzzy."),
        ("DOCUMENT", "Paper info."),
        ("WARN", "Tell danger."),
        ("YOUNG", "Kid baby."),
        ("ARRIVE", "Get there."),
        ("RELY", "Count on."),
        ("PLENTIFUL", "Lots full."),
        ("FLIPPER", "Seal fin."),
        ("FLEXIBLE", "Bend easy."),
        ("FLOOD", "Water everywhere."),
        ("FEAR", "Scared feeling."),
        ("CHIMNEY", "Smoke out."),
        ("PERFORM", "Show do."),
        ("ISLAND", "Water land."),
        ("ACCURATE", "Right exact."),
        ("COMPANION", "Friend buddy."),
        ("PETRIFY", "Scare stone."),
        ("PROOF", "Show true."),
        ("FANCY", "Pretty special."),
        ("EXERT", "Try hard."),
        ("KIN", "Family."),
        ("CHEAT", "Not fair."),
        ("DUPLICATE", "Copy same."),
        ("INDEPENDENT", "Self alone."),
        ("ATTACH", "Stick on."),
        ("NERVOUS", "Worried shake."),
        ("STARTLE", "Scare jump."),
        ("NOBLE", "Kind royal."),
        ("APPETITE", "Hungry want."),
        ("HOMONYM", "Sound same word."),
        ("ABSORB", "Suck in."),
        ("NET", "Catch web."),
        ("DEBATE", "Argue sides."),
        ("FIX", "Repair right."),
        ("DAINTY", "Tiny delicate."),
        ("COWARD", "Scared run."),
        ("INVISIBLE", "Can't see."),
        ("TICKET", "Enter pass."),
        ("COLUMN", "Tall line."),
        ("DEMONSTRATE", "Show how."),
        ("BEHAVE", "Good act."),
        ("BALANCE", "Even steady."),
        ("PRIMARY", "First main."),
        ("DASH", "Quick run."),
        ("BUNGLE", "Mess up."),
        ("JEALOUS", "Want others."),
        ("CROAK", "Frog sound."),
        ("WHIRL", "Spin fast."),
        ("SPOIL", "Rot bad."),
        ("REDUCE", "Make smaller."),
        ("TIDY", "Clean neat."),
        ("DESTRUCTIVE", "Break stuff."),
        ("DIVIDE", "Split parts."),
        ("SHARE", "Give some."),
        ("EQUAL", "Same amount."),
        ("AROMA", "Good smell."),
        ("WISH", "Hope want."),
        ("MAJOR", "Big important."),
        ("SLITHER", "Snake crawl."),
        ("ANTAGONIST", "Story bad guy."),
        ("GRADUAL", "Slow step."),
        ("SOAR", "Fly high."),
        ("LEAP", "Big jump."),
        ("COZY", "Warm comfy."),
        ("FASTEN", "Tie tight."),
        ("RESEMBLE", "Look like."),
        ("ATTITUDE", "Mood way."),
        ("MISERABLE", "Very sad."),
        ("GLOBE", "Earth ball."),
        ("COMMUNITY", "People town."),
        ("FRANTIC", "Wild crazy."),
        ("INTEND", "Plan to."),
        ("BANQUET", "Big dinner."),
        ("POINTLESS", "No use."),
        ("ALTERNATE", "Take turns."),
        ("COLLECT", "Gather up."),
        ("STORMY", "Rain wind."),
        ("LOOSEN", "Make slack."),
        ("SLIPPERY", "Slide easy."),
        ("CREATE", "Make new."),
        ("FREQUENT", "Lots times."),
        ("SUFFIX", "Word end."),
        ("STRUGGLED", "Tried hard."),
        ("VACANT", "Empty free."),
        ("GRIP", "Hold firm."),
        ("FARMER", "Grows food."),
        ("FOOTPRINT", "Foot mark."),
        ("SUMMER", "Hot sun season."),
        ("DELIGHTED", "Super happy."),
        ("ACCESS", "Get in way."),
        ("CONSTRUCT", "Build up."),
        ("SHORE", "Water edge."),
        ("ACCIDENT", "Oops bad."),
        ("BANNER", "Flag sign."),
        ("REASSURE", "Say okay calm."),
        ("CHORE", "Work job."),
        ("SILKY", "Smooth soft."),
        ("VARIETY", "Different kinds."),
        ("SOAPY", "Bubbles clean."),
        ("INJURY", "Hurt body."),
        ("OBSOLETE", "Old no use."),
        ("DIGEST", "Eat break down."),
        ("SHALLOW", "Not deep."),
        ("ANCESTOR", "Old family."),
        ("INSTRUMENT", "Music tool."),
        ("PARDON", "Forgive sorry."),
        ("FIREFLY", "Glow bug."),
        ("WICKED", "Mean bad."),
        ("INDICATE", "Point show."),
        ("TROPICAL", "Hot jungle."),
        ("PREFIX", "Word start."),
        ("SCRUB", "Wash hard."),
        ("DESIGN", "Plan look."),
        ("THRIFTY", "Save money."),
        ("ACTION", "Do move."),
        ("CLIMATE", "Long weather."),
        ("EXPRESS", "Say show."),
        ("INCREASE", "Grow more."),
        ("MAMMAL", "Milk baby animal."),
        ("SURFACE", "Top outside."),
        ("GAZE", "Stare long."),
        ("TEASPOON", "Small spoon."),
        ("SIMPLY", "Just easy."),
        ("FURTHER", "More away."),
        ("NOISY", "Loud sound."),
        ("POEM", "Rhyme words."),
        ("GESTURE", "Hand sign."),
        ("HEROES", "Brave good guys."),
        ("SQUAWK", "Bird yell."),
        ("BOUGH", "Tree branch."),
        ("SOLAR", "Sun power."),
        ("GRIEF", "Deep sad."),
        ("HYPHEN", "Word join dash."),
        ("SPAGHETTI", "Long noodle."),
        ("PRESSURE", "Push hard."),
        ("SAILOR", "Boat worker."),
        ("LISTENING", "Hear careful."),
        ("RECENTLY", "Just now."),
        ("QUOTE", "Repeat say."),
        ("MYTH", "Fake old tale."),
        ("RUMOR", "Untrue talk."),
        ("SAFETY", "No hurt."),
        ("WRESTLE", "Fight grab."),
        ("REHEARSE", "Practice show."),
        ("WHOSE", "Who owns."),
        ("RURAL", "Country farm."),
        ("JEALOUS", "Envy green."),
        ("HEADACHE", "Head hurt."),
        ("GRATEFUL", "Big thanks."),
        ("SEPARATE", "Split apart."),
        ("PARTIAL", "Some not all."),
        ("SCARCELY", "Almost none."),
        ("GOVERNOR", "State boss."),
        ("AMBULANCE", "Sick ride."),
        ("TEMPERATURE", "Hot cold measure."),
        ("SCIENTIFIC", "Science way."),
        ("HANGAR", "Plane house."),
        ("EMERGENCY", "Big problem now."),
        ("INQUIRE", "Ask question."),
        ("MARRIAGE", "Husband wife."),
        ("SWORD", "Fight blade."),
        ("SENTENCE", "Words period."),
        ("MUSEUM", "Old stuff see."),
        ("EXCELLENT", "Best great."),
        ("INGREDIENT", "Recipe part."),
        ("COMFORTABLE", "Cozy nice."),
        ("ESPECIALLY", "Most all."),
        ("LEAGUE", "Team group."),
        ("ANCIENT", "Super old."),
        ("NATIONALITY", "Country from."),
        ("PATIENT", "Wait nice."),
        ("VAULT", "Safe jump."),
        ("HONORABLE", "Good fair."),
        ("STRUGGLING", "Hard try."),
        ("INTERMISSION", "Show break."),
        ("ACQUIRE", "Get have."),
        ("VACUUM", "Suck dirt."),
        ("PERSUADE", "Talk yes."),
        ("MECHANIC", "Fix car."),
        ("REQUIREMENT", "Must need."),
        ("ACCIDENTALLY", "Oops not mean."),
        ("PERFORMANCE", "Show act."),
        ("DISASTROUS", "Big fail."),
        ("SCISSORS", "Cut tool."),
        ("VEGETABLE", "Plant eat."),
        ("APPEARANCE", "Look like."),
        ("STUDIOS", "Movie make."),
        ("DESCENDANT", "Kid family."),
        ("SYSTEMATIC", "Order step."),
        ("AUDIENCE", "Watch crowd."),
        ("VIOLENCE", "Hurt fight."),
        ("UNBELIEVABLE", "Can't true."),
        ("SEPARATELY", "Not together."),
        ("LIGHTNING", "Sky zap."),
        ("UNSUCCESSFUL", "No win."),
        ("INDEPENDENCE", "Free self."),
        ("VARIETY", "Mix kinds."),
        ("ENCYCLOPEDIA", "Fact book."),
        ("IMMEDIATE", "Right now."),
        ("STRENGTHEN", "Make strong."),
        ("NOTICEABLE", "See easy."),
        ("OPERATIONAL", "Works good."),
        ("ACKNOWLEDGEMENT", "Say thanks."),
        ("DESPERATELY", "Need bad."),
        ("COURAGEOUS", "Fearless brave."),
        ("RESTAURANT", "Eat out."),
        ("UNMISTAKABLE", "Clear sure."),
        ("RECYCLABLE", "Reuse trash."),
        ("EXAGGERATE", "Big lie."),
        ("CONVENIENCE", "Easy use."),
        ("PREFERABLE", "Better like."),
        ("MILLIONAIRE", "Rich million."),
        ("RHYTHMIC", "Beat pattern."),
        ("MISCHIEVOUS", "Naughty fun."),
    ]
}
